### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by vivianlys90** [SelfLender/react-native-biometrics#209]
Hi, 

Im using  library with version2.1.29. And currently having this issue in my Crashlytics log.

`Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1882)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1905)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:688)
       at android.app.BackStackRecord.commit(BackStackRecord.java:646)
       at android.app.DialogFragment.show(DialogFragment.java:241)
       at com.rnbiometrics.ReactNativeBiometrics$2.run(ReactNativeBiometrics.java:131)
       at android.os.Handler.handleCallback(Handler.java:938)`

And I found this could be the solution for the issue, hopefully author can add the fixes into latest release.
[https://stackoverflow.com/questions/56358422/java-lang-illegalstateexception-error-in-biometricprompt-authenticate]

**Comment by jayfunk** [comment]
Are you able to recreate this issue so we can confirm it is actually resolved if we were to address this problem?
