### ISSUE TITLE
TypeError: Object is not a constructor (evaluating 'new _reactNativeBiometrics.default()')

### ISSUE THREAD

**Issue by sharma12343** [SelfLender/react-native-biometrics#214]
Facing this issue in IOS after updated Xcode version 12 to 13

**Comment by osbornZ** [comment]
> Facing this issue in IOS after updated Xcode version 12 to 13

I also got this error for version 2.2. It's shouldn't use new, just  ReactNativeBiometrics.xxx like ReactNativeBiometrics.isSensorAvailable() ...  inline contains var ReactNativeBiometrics

**Comment by duttasuraj93** [comment]
> 

tried it that way too, but i have touch id enabled. it still says undefined in `biometryType` result

**Comment by rahulrajsbkk** [comment]
Got The Issue When Upgraded To Xcode 14

**Comment by sharma12343** [comment]
Resolved that issue after added permission for biometric 
react-native-permissions for biometric .

**Comment by vaibhavgadekarapptware** [comment]
I also have this issue @sharma12343 could you please tell me how you resolved this ? in a brief please !

**Comment by rahulrajsbkk** [comment]
The constructor is disabled now you have to use directly from module

**Comment by jayfunk** [comment]
Closing this as it seems the workarounds should work. Re-open a new one if someone else is still having an issue.

**Comment by akkadaya** [comment]
I'm getting that error when testing, can someone share an example of how to mock and test?

**Comment by griffinshuth** [comment]
so the code works when i do this  
const rnBiometrics = new ReactNativeBiometrics();

but when i run my jest tests i get this as an error anyone have any example on how to mock this right or how to fix it?

`
    TypeError: _reactNativeBiometrics.default is not a constructor

      60 |   const [showPassword, setShowPassword] = React.useState(true);
      61 |   const [device, setDevice] = React.useState(null);
    > 62 |   const rnBiometrics = new ReactNativeBiometrics();
         |                        ^
      63 |   const brand = DeviceInfo.getBrand();
      64 |   const systemVersion = DeviceInfo.getSystemVersion();
      65 |   const model = DeviceInfo.getModel();

      at LoginScreen (src/app-sections/login/LoginScreen.js:62:24)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6351:18)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9855:13)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11312:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15811:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15745:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15717:7)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15422:20)
      at flushSyncCallbacks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2597:22)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at Object.act (node_modules/react/cjs/react.development.js:2521:11)
      at act (node_modules/@testing-library/react-native/src/render-act.ts:13:16)
      at render (node_modules/@testing-library/react-native/src/render.tsx:48:33)
      at Object.<anonymous> (__tests__/app-sections/login/login-screen.test.js:85:35)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12)`

**Comment by amahJennifer** [comment]
Mocking the library like this solved the error 

`
jest.mock('react-native-biometrics', () =>
  jest.fn().mockImplementation(() => ({
    isSensorAvailable: jest.fn().mockImplementation(() => ({
      biometryType: '',
    })),
    createSignature: jest.fn(),
    biometricKeysExist: jest.fn().mockImplementation(() => ({
      keysExist: true,
    })),
  })),
);


`
