### ISSUE TITLE
npx react-native run-android build fail after install react-native-biometrics

### ISSUE THREAD

**Issue by saikhantminbhone** [SelfLender/react-native-biometrics#224]
``` warn Package react-native-sqlite-storage contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info JS server already running.
info Installing the app...

> Configure project :
Warning: Please apply google-services plugin at the bottom of the build file.

> Task :app:processDebugResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
295 actionable tasks: 27 executed, 268 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     /Users/saikhantminbhone/Code/java_script/react-native/ToDoProject/android/app/build/intermediates/packaged_manifests/debug/x86_64/AndroidManifest.xml:56: error: resource style/DeviceCredentialHandlerTheme (aka com.todoproject:style/DeviceCredentialHandlerTheme) not found.
     error: failed processing manifest.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     /Users/saikhantminbhone/Code/java_script/react-native/ToDoProject/android/app/build/intermediates/packaged_manifests/debug/x86_64/AndroidManifest.xml:56: error: resource style/DeviceCredentialHandlerTheme (aka com.todoproject:style/DeviceCredentialHandlerTheme) not found.
     error: failed processing manifest.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

    at makeError (/Users/saikhantminbhone/Code/java_script/react-native/ToDoProject/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/saikhantminbhone/Code/java_script/react-native/ToDoProject/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/saikhantminbhone/Code/java_script/react-native/ToDoProject/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/saikhantminbhone/Code/java_script/react-native/ToDoProject/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details. ```
I am having this issues after install react-native-biometrics in my app and re run the project it show above error. Someone Please help me

**Comment by jayfunk** [comment]
It looks like your test app is missing resource style/DeviceCredentialHandlerTheme in the directory or something like that. The manifest if failing to compile due to that issue.

**Comment by c-goettert** [comment]
I am facing the same issue. My app compiled fine but just after adding this package I get the same error.
Indeed I am wondering how this can work for anyone, as `DeviceCredentialHandlerTheme` is not defined in any of the RN default styles (see [default styles.xml of RN 0.70.6](https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.70.6/RnDiffApp/android/app/src/main/res/values/styles.xml)).

Interestingly, when I search my project for `DeviceCredentialHandlerTheme`, I only find some matches in the [react-native-keychain](https://github.com/oblador/react-native-keychain) package, which I also use but which compiled fine with my app before..

However, if I define those styles in the `android/app/src/main/res/values/styles.xml` of my Root-Application, e.g.:
```
<style name="DeviceCredentialHandlerTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="android:textColor">#000000</item>
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
        <item name="android:colorBackground">@color/primary_dark</item>
</style>
```
It seems to be working again. Some relevant versions that I am using:

From package.json:
- react-native: 0.67.5
- react-native-biometrics: 3.0.0

From build.gradle:
- buildToolsVersion = "33.0.0"
- minSdkVersion = 26
- compileSdkVersion = 33
- targetSdkVersion = 33
- ndkVersion = "21.4.7075529"
- androidXCore = "1.6.0"

**Comment by UmarbekSaidov** [comment]
This error happens to me too, after I install this library android build is not working, the above errors are coming

**Comment by luvnishCapgemini** [comment]
Hi @saikhantminbhone @jayfunk @c-goettert @UmarbekSaidov 
Did you find any workaround for this?

**Comment by UmarbekSaidov** [comment]
> Hi @saikhantminbhone @jayfunk @c-goettert @UmarbekSaidov Did you find any workaround for this?

No, I don't have any solution yet
