### ISSUE TITLE
IOS and ANDROID

### ISSUE THREAD

**Issue by mouhsnimohamed** [SelfLender/react-native-biometrics#261]
I installed the library, everything works perfectly locally, but when I tried to generate the build from **appcenter**, I got this error on both ANDROID and IOS :

**ANDROID:**
error Invalid platform "android" selected.
2023-09-01T09:39:51.0017310Z error Bundling failed.
2023-09-01T09:39:51.0017740Z info Available platforms are: "native". If you are trying to bundle for an out-of-tree platform, it may not be installed.
2023-09-01T09:39:51.0018040Z Error: Bundling failed
2023-09-01T09:39:51.0018730Z     at buildBundleWithConfig (/Users/runner/work/1/s/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/buildBundle.js:87:11)
2023-09-01T09:39:51.0019430Z     at buildBundle (/Users/runner/work/1/s/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/buildBundle.js:72:10)
2023-09-01T09:39:51.0020000Z     at async Command.handleAction (/Users/runner/work/1/s/node_modules/@react-native-community/cli/build/index.js:192:9)
2023-09-01T09:39:51.0020420Z info Run CLI with --verbose flag for more details.

**IOS :**
 error Invalid platform "ios" selected.
2023-08-31T09:34:28.8809460Z info Available platforms are: "native". If you are trying to bundle for an out-of-tree platform, it may not be installed.
2023-08-31T09:34:28.8905120Z error Bundling failed.
2023-08-31T09:34:28.8995860Z Error: Bundling failed
2023-08-31T09:34:28.9067560Z     at buildBundleWithConfig (/Users/runner/work/1/s/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/buildBundle.js:87:11)
2023-08-31T09:34:28.9127530Z     at buildBundle (/Users/runner/work/1/s/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/buildBundle.js:72:10)
2023-08-31T09:34:28.9190140Z     at async Command.handleAction (/Users/runner/work/1/s/node_modules/@react-native-community/cli/build/index.js:192:9)

--------------------------------------------------------------------------------------------------------
"react-native": "0.67.5",
"@react-native-community/cli": "^6.0.0",
"@react-native-community/cli-platform-android": "^6.0.0",
"@react-native-community/cli-platform-ios": "^6.0.0",

has anyone faced this issue before

**Comment by rohitiglas** [comment]
As per my understanding, App Center is not giving you the error related to this library (react-native-biometrics).try to generate build from Android studio and Xcode and check.
