### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by marcosrdz** [SelfLender/react-native-biometrics#57]
Loading dependency graph, done.
error: bundling failed: Error: While trying to resolve module `react-native-biometrics` from file `//Documents/GitHub//class/biometrics.js`, the package `/Documents/GitHub//node_modules/react-native-biometrics/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users//Documents/GitHub//node_modules/react-native-biometrics/build/cjs/index.js`. Indeed, none of these files exist:

  * `/Users//Documents/GitHub//node_modules/react-native-biometrics/build/cjs/index.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users//Documents/GitHub//node_modules/react-native-biometrics/build/cjs/index.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (/Users//Documents/GitHub//node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (/Users//Documents/GitHub//node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users//Documents/GitHub//node_modules/metro/src/lib/transformHelpers.js:264:42)
    at dependencies.map.result (/Users//Documents/GitHub//node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users//Documents/GitHub//node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users//Documents/GitHub//node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Documents/GitHub//node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (//Documents/GitHub//node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)

**Comment by acoutts** [comment]
Make sure you do `npm run build` to compile the typescript files into javascript.
