### ISSUE TITLE
Crashing - Fatal Exception: java.lang.NullPointerException 

### ISSUE THREAD

**Issue by ptfly** [SelfLender/react-native-biometrics#72]
I'm having constant crashes on certain android devices.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.hardware.fingerprint.FingerprintManager.getErrorString(int, int)' on a null object reference
       at android.hardware.biometrics.BiometricPrompt.lambda$sendError$0(BiometricPrompt.java:490)
       at android.hardware.biometrics.-$$Lambda$BiometricPrompt$HqBGXtBUWNc-v8NoHYsj2gLfaRw.run(:6)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```
Devices:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/1925966/74412949-247c6c80-4e47-11ea-8312-428d543b24f9.png">

**Comment by kseniamukhortova** [comment]
Same issue reported by Firebase Crashlytics:
`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String android.hardware.fingerprint.FingerprintManager.getErrorString(int, int)' on a null object reference
android.hardware.biometrics.BiometricPrompt.lambda$sendError$0 (BiometricPrompt.java:490)
android.hardware.biometrics.-$$Lambda$BiometricPrompt$HqBGXtBUWNc-v8NoHYsj2gLfaRw.run (Unknown Source:6)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:233)
android.app.ActivityThread.main (ActivityThread.java:7212)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:499)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)`

Device
Brand:OPPO
Model:A1k
Orientation: Portrait
RAM free: 716.68 MB
Disk free: 1.44 GB
Operating System
Version:Android 9
Orientation: Portrait
Rooted:No
